import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "./NextAuthProvider";
import { Providers } from "./providers";
import Navbar from "./components/navigation/Navbar";
import Footer from "./components/footer/Footer";
// import { QueryClient, QueryClientProvider } from "@tanstack/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
// const queryClient = new QueryClient();

export default async function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <NextAuthProvider>
            <Navbar></Navbar>
            {children}
            <Footer></Footer>
          </NextAuthProvider>
        </Providers>
      </body>
    </html>
  );
}

